name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Install Miniconda
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12.6

    # Create and activate the conda environment
    - name: Create conda environment
      run: |
        conda create -n "ci-env" python=3.12.6 gromacs pytest -c conda-forge
      shell: bash -l {0}

    # Run GROMACS simulations in the conda environment
    - name: Run GROMACS simulations
      run: |
        conda activate ci-env
        cd run-pl
        bash commands.dat
        cd ../run-py
        bash commands.dat
      shell: bash -l {0}

    # Run tests
    - name: Run comparison tests
      run: |
        conda activate ci-env
        pytest tests/
      shell: bash -l {0}
